export const calendarEvents = [
  {
    title: "New Year 2024",
    date: "2024-01-01",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Republic Day",
    date: "2024-01-26",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Strategy Sync",
    date: "2024-11-27",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Innovation Jam",
    date: "2024-12-01",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Team Bonding Event",
    date: "2024-11-10",
    type: "event",
    backgroundColor: "rebeccapurple",
  },
  {
    title: "Tech Conference",
    date: "2024-11-25",
    type: "event",
    backgroundColor: "rebeccapurple",
  },
  {
    title: "Eid Al-Adha (Bakri Eid)",
    date: "2024-06-17",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Independance Day",
    date: "2024-08-15",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Ganesh Chaturthi",
    date: "2024-09-07",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Gandhi Jayanti",
    date: "2024-10-02",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Diwali",
    date: "2024-10-31",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Feast Of Saint Fransis Xavior",
    date: "2024-12-03",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Goa Liberation Day",
    date: "2024-12-03",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Christmas",
    date: "2024-12-25",
    type: "holiday",
    backgroundColor: "green",
  },
  {
    title: "Strategy Sync",
    date: "2024-11-27",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Innovation Jam",
    date: "2024-12-01",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Project Kickoff",
    date: "2024-12-05",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Feedback Loop",
    date: "2024-12-10",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Marketing Strategy Review",
    date: "2024-11-15",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Quarterly Sales Planning",
    date: "2024-11-20",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Employee Wellness Workshop",
    date: "2024-11-22",
    type: "event",
    backgroundColor: "rebeccapurple",
  },
  {
    title: "End of Month Wrap-up",
    date: "2024-11-30",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Deep Dive into Q1 Goals",
    date: "2024-11-18",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Product Launch Briefing",
    date: "2024-11-08",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
  {
    title: "Corporate Social Responsibility Planning",
    date: "2024-11-05",
    type: "event",
    backgroundColor: "rebeccapurple",
  },
  {
    title: "HR Policy Review",
    date: "2024-11-13",
    type: "meeting",
    backgroundColor: "#3454D1",
  },
];
