export const dummyData = [
  {
    name: "Allan Silvera",
    department: "Tech",
    paidDays: "21 Days",
    grossPay: "₹58,050",
    statutoryPay: "₹2,165",
    deduction: "₹2,845",
    netPay: "₹53,040",
    status: "Paid",
    payslip: "View",
  },
  {
    name: "Ragesh A C",
    department: "Human Resources",
    paidDays: "23 Days",
    grossPay: "₹78,000",
    statutoryPay: "₹208",
    deduction: "₹4,250",
    netPay: "₹73,542",
    status: "Pending",
    payslip: "View",
  },
  {
    name: "Narshiva Naik",
    department: "Finance",
    paidDays: "22 Days",
    grossPay: "₹62,500",
    statutoryPay: "₹2,845",
    deduction: "₹2,400",
    netPay: "₹57,935",
    status: "Unpaid",
    payslip: "View",
  },
  {
    name: "Kalpesh Naik",
    department: "Tech",
    paidDays: "20 Days",
    grossPay: "₹68,000",
    statutoryPay: "₹3,000",
    deduction: "₹5,000",
    netPay: "₹60,000",
    status: "Paid",
    payslip: "View",
  },
  {
    name: "Nikhil Nagvekar",
    department: "Marketing",
    paidDays: "25 Days",
    grossPay: "₹50,000",
    statutoryPay: "₹1,500",
    deduction: "₹2,000",
    netPay: "₹46,500",
    status: "Pending",
    payslip: "View",
  },
];

export const periods = [
  { month: "Apr 2020", range: "Mar 26 - Apr 25", status: "COMPLETED" },
  {
    month: "May 2020",
    range: "Apr 26 - May 25",
    status: "COMPLETED",
    active: true,
  },
  { month: "Jun 2020", range: "May 26 - Jun 25", status: "COMPLETED" },
  { month: "Jul 2020", range: "Jun 26 - Jul 25", status: "COMPLETED" },
  { month: "Aug 2020", range: "Jul 26 - Aug 25", status: "CURRENT" },
  { month: "Sep 2020", range: "Aug 26 - Sep 25", status: "UPCOMING" },
  { month: "Oct 2020", range: "Sep 26 - Oct 25", status: "UPCOMING" },
  { month: "Nov 2020", range: "Oct 26 - Nov 25", status: "UPCOMING" },
  { month: "Dec 2020", range: "Nov 26 - Dec 25", status: "UPCOMING" },
];
